version: "3.5"
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./build:/app
    working_dir: /app
    command: bash -c "npm install --only=production && node ./index.js"
    environment:
      PORT: "80"
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: db
      TYPEORM_USERNAME: admin
      TYPEORM_PASSWORD: Passw0rd
      TYPEORM_DATABASE: waitinglistdb
      TYPEORM_PORT: "3306"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_ENTITIES: src/entity/**/*.js
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: admin
      MYSQL_PASSWORD: Passw0rd
      MYSQL_DATABASE: waitinglistdb
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
