version: "3.5"
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./build:/app
    working_dir: /app
    command: bash -c "npm start"
    environment:
      - PORT=80
      - DATABASE_URL=mysql://admin:Passw0rd@db/waitinglistdb
      - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: admin
      MYSQL_PASSWORD: Passw0rd
      MYSQL_DATABASE: waitinglistdb
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
